import { makeStyles } from "@mui/styles";

export const bannerStyles = makeStyles((theme) => ({
  banners: {
    width: "100%",
    position: "sticky",
    bottom: "0",
  },
  auth: {
    minHeight: "80px",
    background: theme.palette.primary.main,
    padding: "10px 20px 10px 20px",
  },
  buttons: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  loginTitle: {
    display: "flex !important",
    flexDirection: "column !important",
    alignItems: "center !important",
    justifyContent: "center !important",
    width: "100% !important",
  },
  h2: {
    maxWidth: "700px",
    margin: "0 0 0 0",
    width: "100%",
    color: "white !important",
  },
  p: {
    maxWidth: "700px",
    margin: "0 0 0 0",
    width: "100%",
    color: "white !important",
  },
  login: {
    borderRadius: "60px !important",
    border: "1px solid white !important",
    textTransform: "none !important",
    color: "white !important",
    width: "120px !important",
    fontWeight: "bold !important",
  },
  signup: {
    borderRadius: "60px !important",
    backgroundColor: "white !important",
    textTransform: "none !important",
    color: "black !important",
    width: "120px !important",
    marginLeft: "10px !important",
    fontWeight: "bold !important",
  },
  coockies: {
    minHeight: "150px",
    background: "white",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "20px 20px 20px 20px",
  },
  textCoockiesWrapper: {
    display: "flex",
    flexDirection: "column !important",
    alignItems: "center !important",
  },
  coockieHeader: {
    color: "black",
    margin: "0 0 0 0",
    maxWidth: "700px",
    width: "100%",
    display: "flex",
    justifyContent: "flex-start",
  },
  coockieText: {
    color: "black",
    margin: "5px 0 0 0 0",
    fontSize: "13px",
    maxWidth: "700px",
    left: "0 !important",
  },
  buttonsCoockie: {
    display: "flex",
    flexDirection: "column !important",
    justifyContent: "center !important",
    alignItems: "center !important",
  },
  coockieButton: {
    borderRadius: "60px !important",
    textTransform: "none !important",
    backgroundColor: `${theme.palette.coockie.button} !important`,
    color: "white !important",
    width: "250px !important",
    fontWeight: "bold !important",
  },
}));
