import { makeStyles } from "@mui/styles";

export const sideBarStyles = makeStyles((theme) => ({
  sideBarContainer: {
    boxSizing: "border-box",
    margin: "20px 0 0 20px",
    width: "100%",
    paddingRight: "20px",
  },
  search: {
    marginLeft: 0,
    width: "100%",
    boxSizing: "border-box",
    borderRadius: "60px",
    height: "40px",
    backgroundColor: theme.palette.secondary.main,
    minWidth: "280px",
    maxWidth: "350px",
    marginBottom: "20px",
    display: "flex",
    alignItems: "center",
    position: "relative",
    "&:focus-within": {
      backgroundColor: theme.palette.background.default,
      border: `1px solid ${theme.palette.primary.main}`,
    },
  },
  searchIconWrapper: {
    padding: theme.spacing(0, 2),
    paddingLeft: "15px",
    height: "100%",
    position: "absolute",
    pointerEvents: "none",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  searchIcon: {
    color: theme.palette.text.secondary,
  },
  searchInput: {
    color: "inherit",
    width: "100%",
    "& .MuiInputBase-input": {
      padding: theme.spacing(1, 1, 1, 0),
      paddingLeft: `calc(1em + ${theme.spacing(4)})`,
      transition: theme.transitions.create("width"),
      width: "100%",
    },
  },
  signupWrapper: {
    maxWidth: "350px",
    minWidth: "200px",
    width: "100%",
    marginBottom: "20px",
    boxSizing: "border-box",
    border: `1px solid ${theme.palette.blur.main}`,
    borderRadius: "20px",
    padding: "0px 20px 20px 20px",
  },
  signupButtons: {
    borderRadius: "60px !important",
    backgroundColor: "white !important",
    textTransform: "none !important",
    color: "black !important",
    minWidth: "200px !important",
    height: "40px !important",
    fontWeight: "bold !important",
    fontSize: "16px !important",
    margin: "5px 0 5px 0 !important",
  },
  blueTermsText: {
    padding: "0 0 0 0 !important",
    textTransform: "none !important",
    fontSize: "13px !important",
    "&:hover": {
      "& span": {
        textDecoration: "underline !important",
      },
    },
  },
  termsText: {
    fontSize: "13px",
    color: theme.palette.text.secondary,
  },
  policyTextWrapper: {
    boxSizing: "border-box",
    minWidth: "200px",
    maxWidth: "350px",
    width: "100%",
    marginBottom: "20px",
    marginRight: "20px",
  },
  policyText: {
    color: theme.palette.text.secondary,
    fontSize: "14px",
    whiteSpace: "nowrap",
    marginRight: "10px",
    fontWeight: "500",
    "&:hover": {
      cursor: "pointer",
      textDecoration: "underline",
    },
  },
  copyright: {
    color: theme.palette.text.secondary,
    fontWeight: "500",
    fontSize: "14px",
  },
}));
